{% set name = "mdanse" %}
{% set version = "2.0.0a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/MDANSE-{{ version }}.tar.gz
  sha256: f796584caa64086ab27fb3cf8ec3c3c7def0965ef1620d1cd6169599ef5b2519

build:
  skip: true  # [py<39]
  entry_points:
    - mdanse = MDANSE.Scripts.mdanse:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - wheel
    - sphinx
    - pip
  run:
    - python
    - scipy
    - h5py
    - icecream
    - ase
    - rdkit

test:
  imports:
    - MDANSE
  commands:
    - pip check
    - mdanse --help
  requires:
    - pip

about:
  summary: MDANSE Core package - Molecular Dynamics trajectory handling and analysis code
  home: https://www.isis.stfc.ac.uk/Pages/MDANSEproject.aspx
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
