{% set name = "mdanse" %}
{% set version = "2.0.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3ad1757bf3eba31c6ed2413cfc35766753b1120cf25ad2e4b19e96fc17d9cb2

build:
  skip: true  # [py<39]
  entry_points:
    - mdanse = MDANSE.Scripts.mdanse:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - wheel
    - sphinx
    - pip
  run:
    - mdanalysis
    - mdtraj
    - more-itertools
    - networkx
    - numpy
    - python
    - scipy
    - h5py >=3.13
    - icecream
    - ase
    - rdkit

test:
  imports:
    - MDANSE
  commands:
    - pip check
    - mdanse --help
  requires:
    - pip

about:
  summary: MDANSE Core package - Molecular Dynamics trajectory handling and analysis code
  home: https://www.isis.stfc.ac.uk/Pages/MDANSEproject.aspx
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
