schema_version: 1

context:
  name: mdanse
  version: 2.0.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 71cee6d84d147798a0bb4bf1a7e0c9b6ac09de9352018e7c699b7efdf26caebd

build:
  number: 0
  skip: match(python, "<3.9")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - mdanse = MDANSE.Scripts.mdanse:main

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - wheel
    - sphinx
    - pip
  run:
    - mdanalysis
    - mdtraj
    - more-itertools
    - networkx
    - numpy
    - python
    - scipy
    - h5py >=3.13
    - ase
    - rdkit >=2025.3.3
tests:
  - python:
      imports:
        - MDANSE
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - mdanse --help

about:
  summary: MDANSE Core package - Molecular Dynamics trajectory handling and analysis code
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://www.isis.stfc.ac.uk/Pages/MDANSEproject.aspx

extra:
  recipe-maintainers:
    - jan-janssen
